# Generated by Django 4.2.16 on 2024-10-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customer_address_alter_restaurant_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('APPETIZER', 'Appetizer'), ('SALAD', 'Salad'), ('MAIN_COURSE', 'Main Course')], default='MAIN_COURSE', max_length=50),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.TextField(null=True),
        ),
    ]
